---
- name: "credentials: /etc/config/credentials is present"
  ansible.builtin.file:
    path: /etc/config/credentials
    state: touch
    owner: root
    group: root
    mode: '0644'
    
- name: "credentials: Set ghcr in credentials"
  uci:
    command: set
    key: credentials.ghcr
    value: ghcr

- name: "credentials: Set ghcr_pat in credentials"
  uci:
    command: set
    key: credentials.ghcr
    value:
      ghcr_pat: "{{ ghcr_pat }}"


- name: "credentials: Set ghcr in credentials"
  uci:
    command: set
    key: credentials.notion
    value: notion


- name: "credentials: Set notion_api_key in credentials"
  uci:
    command: set
    key: credentials.notion
    value:
      api_key: "{{ notion_api_key }}"


- name: "credentials: uci commit"
  uci:
    command: commit
