name: glpi

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "1"

services:
  agent:
    image: ghcr.io/sabatligats/iotgw_glpi-agent:latest
    container_name: glpi-agent
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/glpi-agent
      - /dev:/dev
      - /proc:/proc
      - /sys:/sys
    network_mode: host
    privileged: true
    restart: unless-stopped
    # ports:
    #   - 62354:62354
    dns:
      - 192.168.1.16
      - 192.168.210.61
    labels:
      kuma.__container: '{"name": "glpi-agent"}'
    logging: *default-logging
