---
- name: Upgrade to iotgw v1.1.0
  hosts: all
  remote_user: root
  gather_facts: false
  vars:
    local_ip_address: 10.121.100.1
    ip_prefix: "{{ local_ip_address.split('.')[:3] | join('.') }}"
    iotgw_id: "0"
  roles:
    - gekmihesg.openwrt

  tasks:
    - import_tasks: tasks/uptime-kuma.yaml
      tags: uptime-kuma
